name: Sync
on:
  push:
    branches:
      - dev

jobs:
  sync-branches:
    runs-on: ubuntu-20.04
    name: Syncing branches (testing)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Sync Branches PR
        uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SOURCE_BRANCH: "dev"     
          TARGET_BRANCH_STARTS_WITH: "main"
